// <auto-generated />
using System;
using ApplicationCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(UniversityContext))]
    [Migration("20250310150145_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Entity.CourseEntity", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<bool>("Deprecated")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CourseId")
                        .HasName("PK_Course");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entity.CourseModuleEntity", b =>
                {
                    b.Property<int>("CourseModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseModuleId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("CourseModuleId")
                        .HasName("PK_CourseModule");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseModule", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entity.IndividualCourseEntity", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("LearningPlanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("CourseId", "LearningPlanId")
                        .HasName("PK_IndividualCourse");

                    b.HasIndex("LearningPlanId");

                    b.ToTable("IndividualCourse", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entity.LearningPlanEntity", b =>
                {
                    b.Property<int>("LearningPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LearningPlanId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("LearningPlanId")
                        .HasName("PK_LearningPlan");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("LearningPlan", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entity.ModuleMarkEntity", b =>
                {
                    b.Property<int>("CourseModuleId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("Mark")
                        .HasColumnType("int");

                    b.HasKey("CourseModuleId", "StudentId")
                        .HasName("PK_ModuleMark");

                    b.HasIndex("StudentId");

                    b.ToTable("ModuleMark", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entity.StudentEntity", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StudentId")
                        .HasName("PK_Student");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entity.CourseModuleEntity", b =>
                {
                    b.HasOne("Infrastructure.Entity.CourseEntity", "Course")
                        .WithMany("CourseModules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Infrastructure.Entity.IndividualCourseEntity", b =>
                {
                    b.HasOne("Infrastructure.Entity.CourseEntity", "Course")
                        .WithMany("IndividualCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Entity.LearningPlanEntity", "LearningPlan")
                        .WithMany("IndividualCourses")
                        .HasForeignKey("LearningPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("LearningPlan");
                });

            modelBuilder.Entity("Infrastructure.Entity.LearningPlanEntity", b =>
                {
                    b.HasOne("Infrastructure.Entity.StudentEntity", "Student")
                        .WithOne("LearningPlan")
                        .HasForeignKey("Infrastructure.Entity.LearningPlanEntity", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Infrastructure.Entity.ModuleMarkEntity", b =>
                {
                    b.HasOne("Infrastructure.Entity.CourseModuleEntity", "CourseModule")
                        .WithMany("ModuleMarks")
                        .HasForeignKey("CourseModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Entity.StudentEntity", "Student")
                        .WithMany("ModuleMarks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseModule");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Infrastructure.Entity.CourseEntity", b =>
                {
                    b.Navigation("CourseModules");

                    b.Navigation("IndividualCourses");
                });

            modelBuilder.Entity("Infrastructure.Entity.CourseModuleEntity", b =>
                {
                    b.Navigation("ModuleMarks");
                });

            modelBuilder.Entity("Infrastructure.Entity.LearningPlanEntity", b =>
                {
                    b.Navigation("IndividualCourses");
                });

            modelBuilder.Entity("Infrastructure.Entity.StudentEntity", b =>
                {
                    b.Navigation("LearningPlan")
                        .IsRequired();

                    b.Navigation("ModuleMarks");
                });
#pragma warning restore 612, 618
        }
    }
}
